const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('bruxo', {
  pickVideo: () => ipcRenderer.invoke('pick-video'),
  pickOutDir: () => ipcRenderer.invoke('pick-outdir'),
  align: opts => ipcRenderer.invoke('align', opts),
  train: opts => ipcRenderer.invoke('train', opts),
  openFolder: p => ipcRenderer.invoke('open-folder', p),
  savePly: (buf, name) => ipcRenderer.invoke('save-ply', buf, name),
  modelList: () => ipcRenderer.invoke('model-list'),
  modelInstall: k => ipcRenderer.invoke('model-install', k),
  modelRun: (k, input) => ipcRenderer.invoke('model-run', k, input),
  sharp4d: (video, interval) => ipcRenderer.invoke('model-run-sharp4d', video, interval),
  faceAnything4d: (video, maxFrames) => ipcRenderer.invoke('model-run-faceanything', video, maxFrames),
  pickImage: () => ipcRenderer.invoke('pick-image'),
  openPly: () => ipcRenderer.invoke('open-ply'),
  pick4DFolder: () => ipcRenderer.invoke('pick-4d-folder'),
  exportSeq4d: () => ipcRenderer.invoke('export-seq4d'),
  exportSplat4d: () => ipcRenderer.invoke('export-splat4d'),
  convertSeqSplat: () => ipcRenderer.invoke('convert-seq-splat'),
  onDone4d: cb => ipcRenderer.on('done4d', (_e, d) => cb(d)),
  getLang: () => ipcRenderer.invoke('get-lang'),
  setLang: lang => ipcRenderer.invoke('set-lang', lang),
  onMenu: cb => ipcRenderer.on('menu', (_e, a) => cb(a)),
  onStatus: cb => ipcRenderer.on('status', (_e, d) => cb(d)),
  onPreview: cb => ipcRenderer.on('preview', (_e, d) => cb(d)),
  onTrainSnap: cb => ipcRenderer.on('trainsnap', (_e, d) => cb(d)),
  onAligned: cb => ipcRenderer.on('aligned', (_e, d) => cb(d)),
  onDone: cb => ipcRenderer.on('done', (_e, d) => cb(d)),
  onError: cb => ipcRenderer.on('error', (_e, d) => cb(d))
});
