const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('bruxo', {
  pickVideo: () => ipcRenderer.invoke('pick-video'),
  pickOutDir: () => ipcRenderer.invoke('pick-outdir'),
  align: opts => ipcRenderer.invoke('align', opts),
  openColmap: () => ipcRenderer.invoke('open-colmap'),
  saveProject: () => ipcRenderer.invoke('save-project'),
  openProject: () => ipcRenderer.invoke('open-project'),
  train: opts => ipcRenderer.invoke('train', opts),
  abortWork: () => ipcRenderer.invoke('abort-work'),
  openFolder: p => ipcRenderer.invoke('open-folder', p),
  // xform: { s, q:[w,x,y,z], t:[x,y,z] } — a transformação do gizmo já gravada no
  // PLY, para que o sidecar da câmera receba a mesma e continue alinhado.
  savePly: (buf, name, xform) => ipcRenderer.invoke('save-ply', buf, name, xform),
  modelList: () => ipcRenderer.invoke('model-list'),
  modelInstall: k => ipcRenderer.invoke('model-install', k),
  modelRun: (k, input) => ipcRenderer.invoke('model-run', k, input),
  sharp4d: (video, interval) => ipcRenderer.invoke('model-run-sharp4d', video, interval),
  faceAnything4d: (video, maxFrames) => ipcRenderer.invoke('model-run-faceanything', video, maxFrames),
  pickImage: () => ipcRenderer.invoke('pick-image'),
  openPly: () => ipcRenderer.invoke('open-ply'),
  pick4DFolder: () => ipcRenderer.invoke('pick-4d-folder'),
  exportSeq4d: () => ipcRenderer.invoke('export-seq4d'),
  exportSplat4d: () => ipcRenderer.invoke('export-splat4d'),
  convertSeqSplat: () => ipcRenderer.invoke('convert-seq-splat'),
  onDone4d: cb => ipcRenderer.on('done4d', (_e, d) => cb(d)),
  platform: process.platform,
  macToolsStatus: () => ipcRenderer.invoke('mac-tools-status'),
  macToolsInstall: () => ipcRenderer.invoke('mac-tools-install'),
  getVersion: () => ipcRenderer.invoke('get-version'),
  getLang: () => ipcRenderer.invoke('get-lang'),
  setLang: lang => ipcRenderer.invoke('set-lang', lang),
  onMenu: cb => ipcRenderer.on('menu', (_e, a) => cb(a)),
  onStatus: cb => ipcRenderer.on('status', (_e, d) => cb(d)),
  onPreview: cb => ipcRenderer.on('preview', (_e, d) => cb(d)),
  onTrainSnap: cb => ipcRenderer.on('trainsnap', (_e, d) => cb(d)),
  onAligned: cb => ipcRenderer.on('aligned', (_e, d) => cb(d)),
  onDone: cb => ipcRenderer.on('done', (_e, d) => cb(d)),
  onError: cb => ipcRenderer.on('error', (_e, d) => cb(d)),
  onCancelled: cb => ipcRenderer.on('cancelled', () => cb()),
  onProjectOpened: cb => ipcRenderer.on('project-opened', (_e, d) => cb(d))
});
